/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AApp: typeof import('ant-design-vue/es')['App']
    AboutSection: typeof import('./src/components/home/AboutSection.vue')['default']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AFormItemRest: typeof import('ant-design-vue/es')['FormItemRest']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AQrcode: typeof import('ant-design-vue/es')['QRCode']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASegmented: typeof import('ant-design-vue/es')['Segmented']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASlider: typeof import('ant-design-vue/es')['Slider']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    HeadBar: typeof import('./src/components/HeadBar.vue')['default']
    HeroSection: typeof import('./src/components/home/HeroSection.vue')['default']
    MenuItems: typeof import('./src/components/MenuItems.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenuPage: typeof import('./src/components/SideMenuPage.vue')['default']
    ToolCard: typeof import('./src/components/tools/ToolCard.vue')['default']
  }
}

// For TSX support
declare global {
  const AApp: typeof import('ant-design-vue/es')['App']
  const AboutSection: typeof import('./src/components/home/AboutSection.vue')['default']
  const AButton: typeof import('ant-design-vue/es')['Button']
  const ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
  const ACol: typeof import('ant-design-vue/es')['Col']
  const AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
  const ADropdown: typeof import('ant-design-vue/es')['Dropdown']
  const AForm: typeof import('ant-design-vue/es')['Form']
  const AFormItem: typeof import('ant-design-vue/es')['FormItem']
  const AFormItemRest: typeof import('ant-design-vue/es')['FormItemRest']
  const AInput: typeof import('ant-design-vue/es')['Input']
  const AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
  const ALayout: typeof import('ant-design-vue/es')['Layout']
  const ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
  const AMenu: typeof import('ant-design-vue/es')['Menu']
  const AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
  const AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
  const AQrcode: typeof import('ant-design-vue/es')['QRCode']
  const ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
  const ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
  const ARow: typeof import('ant-design-vue/es')['Row']
  const ASegmented: typeof import('ant-design-vue/es')['Segmented']
  const ASelect: typeof import('ant-design-vue/es')['Select']
  const ASlider: typeof import('ant-design-vue/es')['Slider']
  const ASpace: typeof import('ant-design-vue/es')['Space']
  const ASpin: typeof import('ant-design-vue/es')['Spin']
  const ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
  const ASwitch: typeof import('ant-design-vue/es')['Switch']
  const ATag: typeof import('ant-design-vue/es')['Tag']
  const ATextarea: typeof import('ant-design-vue/es')['Textarea']
  const ATooltip: typeof import('ant-design-vue/es')['Tooltip']
  const AUpload: typeof import('ant-design-vue/es')['Upload']
  const HeadBar: typeof import('./src/components/HeadBar.vue')['default']
  const HeroSection: typeof import('./src/components/home/HeroSection.vue')['default']
  const MenuItems: typeof import('./src/components/MenuItems.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SideMenuPage: typeof import('./src/components/SideMenuPage.vue')['default']
  const ToolCard: typeof import('./src/components/tools/ToolCard.vue')['default']
}